### ISSUE TITLE
Corrupted LevelDB in v2.2.0.2

### ISSUE THREAD

**Issue by rikmarais** [Xzotl42/arm5e#302] opened 2023-08-15 14:07 UTC
https://github.com/Xzotl42/arm5e/commit/4dacd52d3d92f86c727adaf6b00b47437e2d8ee8#diff-b2662e6e0e9919152815542019cfb320b60ac40892a32011583c6a177dd66aee corrupts the v11 databases in v2.2.0.2 by partially removing them from the repo. 

They're still included in the v2.2.0.2 release zip and can't be opened in Foundry v11.307 
![image](https://github.com/Xzotl42/arm5e/assets/34374883/b34c572c-de81-4cdb-928e-4013c2794b3e)
![image](https://github.com/Xzotl42/arm5e/assets/34374883/0c10ae8e-2fa6-42e1-8137-719891fe6d70)

I think the right fix here since those packs are no longer intended to be tracked(?) is to remove the levelDB databases entirely, or build them correctly for v11, without corruption.

v2.2.0.0 doesn't have this issue, so this may have been an unintended corruption of the dbs

**Comment by Xzotl42** [comment] 2023-08-15 14:33
Thanks for the report.
Leaving the levelDB files was intended for backward compatibility with V10.
The line added to .gitignore was to stop tracking V11 DB. Ie: just opening the world means 100+ changed files...quite annoying

**Comment by Xzotl42** [comment] 2023-08-15 14:37
I will see what I can do immediately.
Probably leave only the levelDB files and they will be converted at first launch.
Later I need to improve that process or give up v10 compatibility

**Comment by Xzotl42** [comment] 2023-08-15 15:31
A workaround that should work: remove all directories in the pack folder. It will recreate the v11 db at first launch (I just read that's the recommended way to keep v10 compatibility).

**Comment by rikmarais** [comment] 2023-08-15 15:35
Yeah, if the directories aren't already there, then the `nedb` to `leveldb` migration will take care of it 👍
All good then if you guys will remove the corrupted pack folders for the next version, so the v10 stuff can get migrated

**Comment by Xzotl42** [comment] 2023-08-15 18:51
Fixed in release 2.2.1.0

**Closed by Xzotl42** 2023-08-15 18:51 UTC
